options:
  install_sources:
    type: string
    default: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    description: "Elastic Beats apt repository"
  install_keys:
    type: string
    default: D88E42B4
    description: "Elastic Beats apt repository key"
  log_level:
    type: string
    default: "info"
    description: |
      Beats log level. One of debug, info, warning, error, or critical:
      https://www.elastic.co/guide/en/beats/filebeat/5.6/configuration-logging.html#level
  logging_to_syslog:
    type: boolean
    default: true
    description: |
      Send beats logs to syslog:
      https://www.elastic.co/guide/en/beats/filebeat/5.6/configuration-logging.html#_to_syslog
  logstash_hosts:
    type: string
    default: ""
    description: "A comma separated list of logstash output hosts in addition to those from relations."
  logstash_ssl_cert:
    type: string
    default: ""
    description: "Public SSL certificate data (base64 encoded) for connecting securely to logstash."
  logstash_ssl_key:
    type: string
    default: ""
    description: "Private SSL key data (base64 encoded) for connecting security to logstash."
  kafka_hosts:
    type: string
    default: ""
    description: "A comma separated list of kafka output hosts in addition to those from relations."
  kafka_topic:
    type: string
    default: "%{[type]}"
    description: "Topic name. Format strings are allowed."
  kafka_topics:
    type: string
    default: ""
    description: "Expert setting topics filter."
  kafka_version:
    type: string
    default: ""
    description: "Expert setting kafka version."
